// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isLocal = process.env["DATABASE_PROVIDER"] === "sqlite";

export default defineConfig({
  schema: isLocal ? "prisma/schema.sqlite.prisma" : "prisma/schema.prisma",
  migrations: {
    path: isLocal ? "prisma/migrations-sqlite" : "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
